import jsPDF from 'jspdf'

export function exportResponseAsPdf(
  module: string,
  query: string,
  content: string
): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(79, 70, 229) // indigo-600
  doc.text('Scholr', margin, 22)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(107, 114, 128) // gray-500
  doc.text('scholr-coral.vercel.app', margin, 29)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, margin, 35)

  // Divider line
  doc.setDrawColor(229, 231, 235) // gray-200
  doc.line(margin, 39, pageWidth - margin, 39)

  // Module label
  doc.setFontSize(10)
  doc.setTextColor(107, 114, 128)
  doc.text(module.toUpperCase(), margin, 48)

  // Query
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39) // gray-900
  const queryLines = doc.splitTextToSize(query, maxWidth)
  doc.text(queryLines, margin, 56)

  const afterQuery = 56 + queryLines.length * 7 + 8

  // Content
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(55, 65, 81) // gray-700

  // Strip markdown for clean PDF
  const cleaned = content
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`{1,3}([\s\S]*?)`{1,3}/g, '$1')
    .replace(/^\s*[-*+]\s+/gm, '• ')
    .replace(/^\s*\d+\.\s+/gm, (m) => m)
    .trim()

  const lines = doc.splitTextToSize(cleaned, maxWidth)
  let y = afterQuery

  for (const line of lines) {
    if (y > 275) {
      doc.addPage()
      y = 20
    }
    doc.text(line, margin, y)
    y += 5.5
  }

  // Footer on each page
  const pageCount = doc.internal.pages.length - 1
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(156, 163, 175) // gray-400
    doc.text(
      'Generated by Scholr — AI Academic Platform for BTech Students',
      margin,
      287
    )
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, 287)
  }

  const safeName = query
    .slice(0, 30)
    .replace(/[^a-z0-9\s-]/gi, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
  doc.save(`scholr-${module}-${safeName}.pdf`)
}
